Add type substitutions, use in application typing
This doesn't compile due to a bug in eqlog, which crashes at the
following assertion:

 thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `FlatTerm(2)`,
   right: `FlatTerm(1)`', /home/mbid/.cargo/registry/src/github.com-1ecc6299db9ec823/eqlog-0.1.3/src/flatten.rs:127:17

The problem appear to be these axioms:

Axiom NilTypeList() ~> SubstTypes(_, NilTypeList());
Axiom VoidType() ~> SubstType(_, VoidType());
Axiom BooleanType() ~> SubstType(_, BooleanType());
Axiom NumberType() ~> SubstType(_, NumberType());
Axiom StringType() ~> SubstType(_, StringType());

All of these axioms are a reduction from a nullary function to an
expression containing that same nullary function as subexpression.