Bump version (again)
Appears to be necessary to appease crates.io -- with 0.4.1, I get this
error when publishing the eqlog crate:

> cargo publish -p eqlog
error: failed to verify package tarball

Caused by:
  cyclic package dependency: package `eqlog v0.3.0` depends on itself. Cycle:
  package `eqlog v0.3.0`
      ... which satisfies dependency `eqlog = "=0.3.0"` of package `eqlog-eqlog v0.3.2`
      ... which satisfies dependency `eqlog-eqlog = "^0.3.0"` of package `eqlog v0.3.0`